services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env_dev
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env_dev
    ports:
      - "8000:80"
    depends_on:
      - db

  app:
    build:
      context: .
    env_file:
      - .env_dev
    container_name: api_app
    depends_on:
      - db
    command: ["../docker/app.sh"]
    ports:
      - 1234:8000

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - app
