services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env_dev
    ports:
      - 5432:5432
    volumes:
      - ./tests/data.sql:/docker-entrypoint-initdb.d/data.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env_dev
    ports:
      - "8000:80"
    depends_on:
      - db

  app:
    build:
      context: .
    env_file:
      - .env_dev
    container_name: api_app
    depends_on:
      - db
    command: ["../docker/app.sh"]
    ports:
      - 1234:8000