services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env_dev
    ports:
      - 5432:5432

  app:
    build:
      context: .
    env_file:
      - .env_dev
    container_name: api_app
    depends_on:
      - db
    command: ["../docker/app.sh"]
    ports:
      - 1234:8000