services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "harddb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ./database/database.sql
    ports:
      - "5432:5432"
