services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env_dev
    ports:
      - 5432:5432
    volumes:
      - ./static:/static

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env_dev
    ports:
      - "8000:80"
    depends_on:
      - db

  app:
    build:
      context: .
    env_file:
      - .env_dev
    container_name: api_app
    depends_on:
      - db
    command: ["../docker/app.sh"]
    ports:
      - "1234:8000"
    volumes:
      - ./src:/apping/src

  nginx:
    container_name: "nginx"
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
      - pgadmin
      - db
    links:
      - app

#  redis:
#    image: redis:latest
#    container_name: redis_app
#    ports:
#      - "6379:6379"