"""mode grop owner

Revision ID: 3301100de5bf
Revises: 3c6d6879fe43
Create Date: 2024-05-16 17:59:40.924995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3301100de5bf'
down_revision: Union[str, None] = '3c6d6879fe43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('group_user_id_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['owner_id'], ['id'])
    op.drop_column('group', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_user_id_fkey', 'group', 'user', ['user_id'], ['id'])
    op.drop_column('group', 'owner_id')
    # ### end Alembic commands ###
