"""add thing and parameters

Revision ID: 60a998a5dbe9
Revises: 2c8cf9ec3760
Create Date: 2024-05-13 21:54:04.201505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a998a5dbe9'
down_revision: Union[str, None] = '2c8cf9ec3760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_key'), 'parameter', ['key'], unique=False)
    op.create_index(op.f('ix_parameter_value'), 'parameter', ['value'], unique=False)
    op.create_table('thing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thing_title'), 'thing', ['title'], unique=False)
    op.create_table('thing_parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameter.id'], ),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing_parameter')
    op.drop_index(op.f('ix_thing_title'), table_name='thing')
    op.drop_table('thing')
    op.drop_index(op.f('ix_parameter_value'), table_name='parameter')
    op.drop_index(op.f('ix_parameter_key'), table_name='parameter')
    op.drop_table('parameter')
    # ### end Alembic commands ###
